### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by NicTanghe** [samm00/penrose#1]
Hello i am looking to use the penrose pattern as a moving noise generator.
Your code seems to be the only one using vertex information to tile indefinatly.

When i try to run it i get the error.
And i was wondering if my python version has anything to do with it.

``` File "C:\Users\nicta\git\penrose\penrose.py", line 94
    p4 =
         ^
SyntaxError: invalid syntax```

**Comment by samm00** [comment]
Hey, sorry about that.

Looks like a syntax error on my part (that didn't need to be there).

Just fixed it.

Just deleting that line is fine.

Also keep me posted!! I'm so happy someone is using something of mine, I'd love to see what you create! (Am a current CS student and this exchange is currently the highlight of my CS career)

**Comment by NicTanghe** [comment]
Don't apologise for making a mistake in something you gave them 4 free to a complete stranger.
I`ll have a look when I have time i'm currently working for my exams.
